name: clind
description: A new Flutter project.
version: 1.0.0+1
publish_to: none

environment:
  sdk: 3.8.1
  flutter: 3.32.8

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  tool_clind_theme:
    path: ../../tool/clind/theme

dev_dependencies:
  flutter_lints: 3.0.1